#!/bin/bash

language=German

while getopts "l:" flag; do
case "$flag" in
    l)language=$OPTARG;;
esac
done

filename=${@:$OPTIND:1}

#Track-ID des Untertitels suchen
line=`mediainfo "$filename" | grep -A 5 Text | grep -B 5 -m 1 $language | grep -m 1 ID`
lineArray=($line)
trackId=${lineArray[2]}
if [ -z "$trackId" ]
then
  echo "Kein Untertitel in der Sprache $language vorhanden."
  exit
fi
echo "Track-ID: $trackId"

line=`mkvinfo "$filename" | grep "Spurnummer: $trackId"`
lineArray=($line)
mkvTrackId=${lineArray[9]/)/}
echo "MKV-Track-ID: $mkvTrackId"

#Name der Untertitel-Datei
name=`basename "$filename" .mkv`-$language

mkvextract tracks "$filename" $mkvTrackId:"$name".sup
bdsup2subpp "$name".sup -o "$name".sub
vobsub2srt --verbose "$name"

rm "$name".sup
rm "$name".sub
rm "$name".idx
