#!/bin/bash

crf=18
preset=slow
tune=film

while getopts "c:p:t:" flag; do
case "$flag" in
    c)crf=$OPTARG;;
    p)preset=$OPTARG;;
    t)tune=$OPTARG;;
esac
done

filename=${@:$OPTIND:1}

crop=`cropdetect "$filename"`
cropForFilename=`echo "$crop"|sed -e 's/:/x/g'`
destination=$preset-crf$crf-crop$cropForFilename-"$filename"

echo crf=$crf
echo preset=$preset
echo crop=$crop
echo tune=$tune
echo destination=$destination

ffmpeg -i "$filename" -preset $preset -tune $tune -c:v libx264 -crf $crf -vf crop=$crop -c:a copy -c:s copy -map 0 "$destination"
